### ISSUE TITLE
prefer functional components

### ISSUE THREAD

**Issue by Yarin-C** [ItayHalaf/portfolio#1]
https://github.com/ItayHalaf/portfolio/blob/740342d952d93ee04ecd8d5d658ded62ca8da2f3/src/App.js#L5

although this is "App" it's a stateless component, and should be converted to a functional component.:

```
funciotn App() {
    return (
      <div className="App">
        <Portfolio />
      </div>
    );
}
```

**Comment by ItayHalaf** [comment]
done
