### ISSUE TITLE
Lengthy props

### ISSUE THREAD

**Issue by ghost** [ItayHalaf/portfolio#13]
https://github.com/ItayHalaf/portfolio/blob/740342d952d93ee04ecd8d5d658ded62ca8da2f3/src/portfolio.js#L119

Try to avoid passing too much logic into props. in this instance, it would be better to export:

this.state.items.filter(item => item.id === this.state.activeId.toString())[0]

to a separate function or const

**Comment by ItayHalaf** [comment]
done
