### ISSUE TITLE
Shadowing html element props

### ISSUE THREAD

**Issue by ghost** [ItayHalaf/portfolio#5]
https://github.com/ItayHalaf/portfolio/blob/740342d952d93ee04ecd8d5d658ded62ca8da2f3/src/edit-add-component.js#L59

I'm not sure if you intended on doing this or not, but dont use props in your code which are named as html props (here you're assigning id to input which is an html prop, and you're using id in your handleChange method).

what you should do instead, is pass you props to the handlers like so:

```
handleChange(inputId) = event => {
    this.setState({
      [inputId]: event.target.value
    });
  };

  render() {
    const { title, url, description } = this.state;
    return (
      <div className="layoutContainer">
        <label>url: <input value={url} type="text" onChange={(this.handleChange("url")}/></label>
        ...
      </div>
    );
  }
```

**Comment by ItayHalaf** [comment]
done
